general {
        colors = true
        interval = 5
        output_format = "i3bar"
}

order += "ipv6"
order += "ethernet enp4s0"
order += "disk /"
order += "load"
order += "memory"
order += "disk /media/lelloman/70c65675-682e-490a-808b-abd9757b98e2"
order += "tztime local"

ipv6 {
        format_up = "IPv6: %ip"
        format_down = "no IPv6"
}

ethernet enp4s0 {
        format_up = "🌐 %ip (%speed)"
        format_down = "🌐 down"
}

disk "/" {
        format = "🛢️ %avail (%percentage_avail)"
}

load {
        format = "🧠 %1min"
}

memory {
        format = "🗄️ %available"
        threshold_degraded = "1G"
        format_degraded = "🗄️ LOW %available"
}

disk "/media/lelloman/70c65675-682e-490a-808b-abd9757b98e2" {
        format = "🛢️ %avail"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}
