# Native Wayland application assignments.
assign [app_id="^chromium$"] 1
assign [app_id="^code$"] 2
assign [app_id="^jetbrains-studio$"] 5

# XWayland fallbacks.
assign [class="^Chromium$"] 1
assign [class="^Code$"] 2
assign [class="^jetbrains-studio$"] 5
